import { useState } from "react";
import { Modal, PageHeader } from "../components/index.jsx";
import { useApp } from "../context/AppContext.jsx";
import { parseICSCalendar } from "../utils/helpers.js";
import { CalendarDays, MessageSquare, FileText, Shield, DollarSign, Repeat, Calculator, Sparkles, Bell, TrendingUp, HeartPulse, ClipboardList, Camera, Wrench } from "lucide-react";

const TOOLS=["calendar","quote","message","cleaner","proof","owner","deposit","alerts","forecast","pricing","ltv","repeat","approval","tax","health"];
const META={calendar:["Calendar Sync",CalendarDays,"bookings"],quote:["Direct Booking Quote Generator",DollarSign,"leads"],message:["Smart Message Assistant",MessageSquare,"messages"],cleaner:["Cleaner Task View",ClipboardList,"cleaning"],proof:["Photo Proof",Camera,"maintenance"],owner:["Owner Portal",FileText,"owner-report"],deposit:["Damage & Deposit Tracker",Shield,"booking-calendar"],alerts:["Smart Alerts Center",Bell,"dashboard"],forecast:["Profit Forecast",TrendingUp,"revenue"],pricing:["Dynamic Pricing Notes",Sparkles,"booking-calendar"],ltv:["Guest Lifetime Value",HeartPulse,"guest-crm"],repeat:["Repeat Guest Campaigns",Repeat,"guest-crm"],approval:["Maintenance Approval",Wrench,"maintenance"],tax:["Tax/GCT Preparation Pack",Calculator,"tax-reserve"],health:["Host Health Score",HeartPulse,"dashboard"]};
const uid=(p)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
const copy=async(t)=>{try{await navigator.clipboard.writeText(t);return true;}catch{return false;}};

export default function SmartTools({setPage}){
  const {properties,bookings,guests,cleaning,maintenance,supplies,expenses,leads,settings,setBookings,setCleaning,setMaintenance,setQuotes,quotes=[]}=useApp();
  const [tool,setTool]=useState(""); const [status,setStatus]=useState("");
  const [state,setState]=useState({property_id:"",lead_id:"",guest_id:"",booking_id:"",ics:"",message:"",title:"",url:""});
  const [events,setEvents]=useState([]); const [selectedEvent,setSelectedEvent]=useState("");
  const pullSummary=`Records loaded • Properties:${properties.length} Bookings:${bookings.length} Guests:${guests.length} Cleaning:${cleaning.length} Maintenance:${maintenance.length} Supplies:${supplies.length} Expenses:${expenses.length} Leads:${leads.length}`;

  const runPrimary=()=>{if(tool==="calendar"){if(!state.ics)return setStatus("Error: paste ICS data first."); const parsed=parseICSCalendar(state.ics)||[]; setEvents(parsed); setStatus(`Success: parsed ${parsed.length} events.`); return;} if(tool==="cleaner"&&state.booking_id){setCleaning([...(cleaning||[]),{id:uid('cl'),booking_id:state.booking_id,cleaning_status:'In Progress'}]);setStatus('Success: cleaning task started.');return;} setStatus(`Success: ${META[tool][0]} primary action ran.`);};
  const runSave=()=>{if(tool==="calendar"){if(!state.property_id||!selectedEvent)return setStatus('Error: select property and imported event.'); const ev=events.find(e=>e.event_id===selectedEvent); setBookings([...(bookings||[]),{id:uid('bk'),booking_id:uid('bk'),property_id:state.property_id,platform:'Other',booking_status:'Confirmed',payment_status:'Pending',guest_name:ev?.summary||'Imported Guest',checkin_date:ev?.checkin_date,checkout_date:ev?.checkout_date,source_notes:'Converted from imported calendar event'}]); setStatus('Success: booking created from imported event.');return;} if(tool==="quote"){const lead=leads.find(l=>l.id===state.lead_id); const payload={id:uid('qt'),guest_name:lead?.lead_name||'Manual Guest',property_id:state.property_id}; setQuotes([...(quotes||[]),payload]); setStatus('Success: quote saved.'); return;} setStatus(`Success: ${META[tool][0]} data saved.`);};

  const secondary = <div className='smart-tool-actions'><button className='btn-primary' onClick={runPrimary}>Run Workflow</button><button className='btn-secondary' onClick={runSave}>Save / Update</button><button className='btn-secondary' onClick={async()=>setStatus((await copy(`${META[tool][0]}\n${pullSummary}`))?'Success: copied summary.':'Error: copy failed.')}>Copy</button><button className='btn-secondary' onClick={()=>{const w=window.open('','_blank'); if(!w)return setStatus('Error: popup blocked.'); w.document.write(`<h1>Host Operations</h1><p>${META[tool][0]}</p><p>${pullSummary}</p>`); w.document.close(); w.print(); setStatus('Success: export opened.');}}>Export PDF</button><button className='btn-ghost' onClick={()=>setPage?.(META[tool][2])}>Go to related page</button></div>;

  const modalBody=<section className='smart-tool-modal-section'><p>{pullSummary}</p><div className='smart-tool-form-grid'><div className='field'><label>Property</label><select value={state.property_id} onChange={e=>setState({...state,property_id:e.target.value})}><option value=''>Select</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className='field'><label>Lead</label><select value={state.lead_id} onChange={e=>setState({...state,lead_id:e.target.value})}><option value=''>Select</option>{leads.map(l=><option key={l.id} value={l.id}>{l.lead_name}</option>)}</select></div><div className='field'><label>Booking</label><select value={state.booking_id} onChange={e=>setState({...state,booking_id:e.target.value})}><option value=''>Select</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.guest_name||b.id}</option>)}</select></div><div className='field'><label>Guest</label><select value={state.guest_id} onChange={e=>setState({...state,guest_id:e.target.value})}><option value=''>Select</option>{guests.map(g=><option key={g.id} value={g.id}>{g.guest_name}</option>)}</select></div></div>{tool==='calendar'&&<><textarea rows={6} value={state.ics} onChange={e=>setState({...state,ics:e.target.value})} placeholder='Paste ICS data'/><table><tbody>{events.map(e=><tr key={e.event_id}><td><input type='radio' checked={selectedEvent===e.event_id} onChange={()=>setSelectedEvent(e.event_id)}/></td><td>{e.summary}</td><td>{e.checkin_date}</td><td>{e.checkout_date}</td></tr>)}</tbody></table></>}{secondary}</section>;

  return <div className='page'><PageHeader title='Smart Tools' subtitle='All tools execute inside modals with data, save/copy/export, and feedback.'/><div className='smart-tools-grid'>{TOOLS.map(k=>{const [t,Icon,p]=META[k];return <div className='card smart-tool-card' key={k}><div className='smart-tool-card-header'><Icon size={16}/><h3 className='section-title'>{t}</h3></div><p className='text-muted'>Open modal workflow with app-state actions.</p><div className='smart-tool-actions'><button className='btn-primary' onClick={()=>{setTool(k);setStatus('Ready.')}}>Open</button><button className='btn-ghost' onClick={()=>setPage?.(p)}>Go to related page</button></div></div>})}</div><Modal open={!!tool} onClose={()=>setTool('')} title={tool?META[tool][0]:''} wide><p className='smart-tool-status'>{status||'Ready.'}</p>{modalBody}</Modal></div>
}
